import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./providers/provider";
import Navbar from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PlayGround App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body >
        <Provider>
          <div className="flex-1 ml-64">
            <Navbar />
            <main className="pt-16 p-4">
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
